# Generated by Django 4.0.4 on 2022-05-26 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='user_task', to=settings.AUTH_USER_MODEL, verbose_name='Auther'),
            preserve_default=False,
        ),
    ]
